# -*- coding: utf-8 -*-
"""Analise_Clima_Araras

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MJo3X81nU9OgQaXYojSg8c7iFedfozqT

## ATIVIDADE EXTENSIONISTA IV

### Análise de Dados Climáticos de Araras e Percepção da Sociedade.

DAVID MAIA SOUZA - 4152257
"""

# Importando as bibliotecas
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Importando os dados
dataset = pd.read_csv("nasapower_Araras.csv")
dados = dataset.copy()
display(dados.head())

# Renomeando as colunas
dados = dados.rename(columns={"YEAR":"ANO", "MO":"MÊS", "DY":"DIA","T2M_MIN": "TEMP. MÍNIMA","T2M_MAX": "TEMP. MÁXIMA",  "T2M": "TEMP. MÉDIA", "PRECTOTCORR":"CHUVA" })
display(dados.head(-5))

# Criando uma coluna "DATA" para juntar dia, mês e ano
dados["DATA"] = dados["DIA"].astype(str) + '-' + dados["MÊS"].astype(str) + '-' + dados["ANO"].astype(str)

# Selecionando o intervalo de 1981 até 2025 (excluindo dados de 2026)
dados = dados.loc[dados["ANO"] != 2026]
display(dados)

# Agrupando o total de chuva anual
chuva_por_ano = dados.groupby("ANO")["CHUVA"].sum().reset_index()

plt.figure(figsize=(15, 6))

# Gráfico de barras com a paleta "mako"
ax = sns.barplot(x="ANO", y="CHUVA", data=chuva_por_ano, alpha=0.8, palette="mako")

# Linha de tendência
x_indices = np.arange(len(chuva_por_ano))
y_valores = chuva_por_ano["CHUVA"]
m_chuva, c_chuva = np.polyfit(x_indices, y_valores, 1)

# Plotando a linha de tendência
plt.plot(x_indices, m_chuva * x_indices + c_chuva, color="red", linestyle="--", linewidth=2.5, label="Tendência")

# Plotando gráfico de barras de precipitação anual
plt.title("Precipitação Total por Ano em Araras (1981 - 2025)",fontsize=14)
plt.ylabel("Precipitação Total (mm)")
plt.xlabel("") # forçando não escrever
plt.xticks(rotation=90)
plt.grid(axis="y", linestyle="--", alpha=0.5)
plt.legend()
plt.show()

# Agrupando a temperatura média anual
temp_media_por_ano = dados.groupby("ANO")["TEMP. MÉDIA"].mean().reset_index()

plt.figure(figsize=(15, 6))

# Gráfico de Linhas
ax = sns.lineplot(x="ANO",y="TEMP. MÉDIA",data=temp_media_por_ano, marker="o",markersize=6 , palette="light_blue")

# Linha de Tendência
x_indices = temp_media_por_ano["ANO"]
y_valores = temp_media_por_ano["TEMP. MÉDIA"]
m, c = np.polyfit(x_indices, y_valores, 1) # Ajuste linear

# Plotando a linha de tendência
plt.plot(x_indices, m*x_indices + c, color='red', linestyle='--', linewidth=2, label="Tendência")

# Plotando o Gráfico de Linhas
plt.title("Temperatura Média Anual em Araras (1981 - 2025)", fontsize=14)
plt.ylabel("Temperatura Média (°C)")
plt.xlabel("") # forçando não escrever
plt.xticks(x_indices, rotation=90)
plt.grid(axis="y", linestyle="--", alpha=0.5)
plt.legend()
plt.show()

# Agrupando a temperatura máxima anual
temp_maxima_por_ano = dados.groupby("ANO")["TEMP. MÁXIMA"].max().reset_index()

plt.figure(figsize=(15, 6))

# Gráfico de Linhas
ax = sns.lineplot(x="ANO",y="TEMP. MÁXIMA",data=temp_maxima_por_ano, marker="o",markersize=6 , palette="light_blue")

# Linha de Tendência
x_indices = temp_maxima_por_ano["ANO"]
y_valores = temp_maxima_por_ano["TEMP. MÁXIMA"]
m, c = np.polyfit(x_indices, y_valores, 1) # Ajuste linear

# Plotando a linha de tendência
plt.plot(x_indices, m*x_indices + c, color='red', linestyle='--', linewidth=2, label="Tendência")


# Plotando o Gráfico de Linhas
plt.title("Temperatura Máxima Anual em Araras (1981 - 2025)", fontsize=14)
plt.ylabel("Temperatura Máxima (°C)")
plt.xlabel("") # forçando não escrever
plt.xticks(x_indices, rotation=90)
plt.grid(axis="y", linestyle="--", alpha=0.5)
plt.xticks(rotation=90)
plt.legend()
plt.show()

# Agrupando a temperatura máxima anual
temp_minima_por_ano = dados.groupby("ANO")["TEMP. MÍNIMA"].min().reset_index()

plt.figure(figsize=(15, 6))

# Gráfico de Linhas
ax = sns.lineplot(x="ANO",y="TEMP. MÍNIMA",data=temp_minima_por_ano, marker="o",markersize=6 , palette="light_blue")

# Linha de Tendência
x_indices = temp_minima_por_ano["ANO"]
y_valores = temp_minima_por_ano["TEMP. MÍNIMA"]
m, c = np.polyfit(x_indices, y_valores, 1) # Ajuste linear

# Plotando a linha de tendência
plt.plot(x_indices, m*x_indices + c, color='red', linestyle='--', linewidth=2, label="Tendência")


# Plotando o Gráfico de Linhas
plt.title("Temperatura Mínima Anual em Araras (1981 - 2025)", fontsize=14)
plt.ylabel("Temperatura Mínima (°C)")
plt.xlabel("") # forçando não escrever
plt.xticks(x_indices, rotation=90)
plt.grid(axis="y", linestyle="--", alpha=0.5)
plt.xticks(rotation=90)
plt.legend()
plt.show()